receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:  # Batch processor để gom nhóm metrics trước khi gửi đi

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: spring
  otlp:
    endpoint: tempo:4317  # Tempo container host và port
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]  # Metrics sẽ được xuất qua Prometheus
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]  # Traces sẽ được xuất qua OTLP tới Tempo
    logs:
      receivers: [otlp]
      exporters: [loki, logging]  # Logs sẽ được xuất tới Loki và log
