global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'
        title: '{{ .CommonAnnotations.summary }}'
        text: >-
          *Alert:* {{ .CommonLabels.alertname }}
          *Instance:* {{ .CommonLabels.instance }}
          *Description:* {{ .CommonAnnotations.description }}
          *Status:* {{ .Status }}
